#!/usr/bin/bash

./plot-trento-events d Au 9 --random-seed 4 -p -1.0 -k 9999 -w 0.6 -d 0.6 -x 4.2 --grid-max 6 --grid-step 0.05
pdfcrop plot.pdf dAu_-1p0.pdf

./plot-trento-events d Au 9 --random-seed 4 -p -0.8 -k 9999 -w 0.6 -d 0.6 -x 4.2 --grid-max 6 --grid-step 0.05
pdfcrop plot.pdf dAu_-0p8.pdf

./plot-trento-events d Au 9 --random-seed 4 -p -0.6 -k 9999 -w 0.6 -d 0.6 -x 4.2 --grid-max 6 --grid-step 0.05
pdfcrop plot.pdf dAu_-0p6.pdf

./plot-trento-events d Au 9 --random-seed 4 -p -0.4 -k 9999 -w 0.6 -d 0.6 -x 4.2 --grid-max 6 --grid-step 0.05
pdfcrop plot.pdf dAu_-0p4.pdf

./plot-trento-events d Au 9 --random-seed 4 -p -0.2 -k 9999 -w 0.6 -d 0.6 -x 4.2 --grid-max 6 --grid-step 0.05
pdfcrop plot.pdf dAu_-0p2.pdf

./plot-trento-events d Au 9 --random-seed 4 -p 0.0 -k 9999 -w 0.6 -d 0.6 -x 4.2 --grid-max 6 --grid-step 0.05
pdfcrop plot.pdf dAu_0p0.pdf

./plot-trento-events d Au 9 --random-seed 4 -p 0.2 -k 9999 -w 0.6 -d 0.6 -x 4.2 --grid-max 6 --grid-step 0.05
pdfcrop plot.pdf dAu_0p2.pdf

./plot-trento-events d Au 9 --random-seed 4 -p 0.4 -k 9999 -w 0.6 -d 0.6 -x 4.2 --grid-max 6 --grid-step 0.05
pdfcrop plot.pdf dAu_0p4.pdf

./plot-trento-events d Au 9 --random-seed 4 -p 0.6 -k 9999 -w 0.6 -d 0.6 -x 4.2 --grid-max 6 --grid-step 0.05
pdfcrop plot.pdf dAu_0p6.pdf

./plot-trento-events d Au 9 --random-seed 4 -p 0.8 -k 9999 -w 0.6 -d 0.6 -x 4.2 --grid-max 6 --grid-step 0.05
pdfcrop plot.pdf dAu_0p8.pdf

./plot-trento-events d Au 9 --random-seed 4 -p 1.0 -k 9999 -w 0.6 -d 0.6 -x 4.2 --grid-max 6 --grid-step 0.05
pdfcrop plot.pdf dAu_1p0.pdf
